### ISSUE TITLE
非本地查看SQL的时候，推荐：spring.jpa.show-sql=false

### ISSUE THREAD

**Issue by zhangzhenhuajack** [zhangzhenhuajack/spring-data-jpa-guide#39]
改成：
````
改成，如下即可：
spring.jpa.show-sql=false;
logging.level.org.hibernate.SQL=DEBUG
````
这样 sql就会通过logback的形式打印出来，会带上traceId,threadID等上下文信息；
![image](https://user-images.githubusercontent.com/11462004/136913767-599f2b75-1183-46ce-b65d-7e33485d8dc8.png)

**Comment by zhangzhenhuajack** [comment]
可以体验一下如下配置
````
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.engine.QueryParameters: debug
    org.hibernate.engine.query.HQLQueryPlan: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
````
![image](https://github.com/zhangzhenhuajack/spring-data-jpa-guide/assets/11462004/b98ef0b0-6209-4d56-bec1-d989217187a9)

更详细的参考：https://blog.csdn.net/qq_35387940/article/details/102563845
